### ISSUE TITLE
Is train.py tested or updated?

### ISSUE THREAD

**Issue by gyzou** [harryhan618/SCNN_Pytorch#15]
There are some obvious errors in the train.py, such as

ln 29, exp_name = exp_dir.split['/'][-1]

ln 155, img = cv2.resize(img, (800, 288)

Are you training with a different script? I just want to make sure the train.py in the repo can work as expected. Thanks for sharing your code.

**Comment by harryhan618** [comment]
Sorry, I train my model on the PC which has access to GPU while I update my code for pushing to this repo on another PC. So some changes may get omitted.
Please feel free to feedback to me about those bugs. Appreciated!

**Comment by chixma** [comment]
@harryhan618 And in train.py, lr_scheduler.step() is wrongly called in every iteration? I think it should be called after an epoch, but not an iteration. Will you update to the lastest codes on your PC that has access to GPU?

**Comment by gyzou** [comment]
I usually use "meld" to track differences between two codebases. Recommend.

**Comment by harryhan618** [comment]
@chixma No, lr_scheduler does update every iteration. Because the training dataset is very large (80k images). I use poly scheme to decrease the lr. So all you need  to do is to adjust the total iteration time rather than total training epoch time ( `"max_iter": 8000`  in cfg.json). 

You can also set a `min_lrs` so that after annealing to the `min_lrs` after `max_iter`, you can keep training at a low lr (details in `lr_scheduler.py`). But due to my experience, best practice is to anneal to 0 (i.e. set `min_lrs=0`), and choose a good initial `lr` and `max_iter`.

**Comment by harryhan618** [comment]
@gyzou Thanks. My codebase is liable to change because currently I'm doing a project about lane detection. But I think the basic functionality is complete for this repo. Hope all things run fine.
